CREATE TABLE ecommerce_sales_advanced (
    order_id VARCHAR(20) PRIMARY KEY,
    order_date DATE NOT NULL,
    customer_id VARCHAR(20) NOT NULL,
    category VARCHAR(100),
    product VARCHAR(100),
    region VARCHAR(50),
    city VARCHAR(100),
    channel VARCHAR(50),
    quantity INT,
    unit_price NUMERIC(12,2),
    discount NUMERIC(6,4),
    gross_sales NUMERIC(14,2),
    revenue NUMERIC(14,2),
    cost NUMERIC(14,2),
    payment_method VARCHAR(50),
    order_status VARCHAR(30),
    profit NUMERIC(14,2),
    profit_margin NUMERIC(8,4),
    month VARCHAR(7),
    year INT,
    quarter VARCHAR(2),
    is_completed INT,
    is_returned INT,
    is_cancelled INT
);
